/*
 * Homologs.java
 *
 * Created on June 5, 2001, 5:50 PM
 *
 * Stores the homologs generated by FlexSeqAnalyzer class.
 */

package edu.harvard.med.hip.flex.util;

import java.util.Vector;

/**
 *
 * @author  dzuo
 * @version 
 */
public class Homologs {
    private Vector homolog;
    private BlastResults blastResults;
    
    /** Creates new Homologs */
    public Homologs() {}

    /**
     * Set the homolog field to the given value.
     *
     * @param homolog The value to be set to.
     */
    public void setHomolog(Vector homolog) {
        this.homolog = homolog;
    }
    
    /**
     * Returns the homolog field.
     *
     * @return The homolog field.
     */
    public Vector getHomolog() {
        return homolog;
    }
    
    /**
     * Set the blastResults field to the given value.
     *
     * @param blastResults The value to be set to.
     */
    public void setBlastResults(BlastResults blastResults) {
        this.blastResults = blastResults;
    }
    
    /**
     * Returns the blastResults field.
     *
     * @return The blastResults field.
     */
    public BlastResults getBlastResults() {
        return blastResults;
    }
}
