<%@page contentType="text/html"%>
<html>
<head><title>JSP Page</title></head>
<body>
<pre>
22	Homo sapiens	69	2327	2259	1006	NA	Xq12-q13	atctaggctcagttatgtttactaacatgaatcttacttaacagcatgaggcaagatctaggctcaagatggcgctgctcgcgatgcattcttggcgctgggcggccgcggcggctgctttcgaaaagcgccggcactccgcgattctgatccggcctttagtctctgttagcggctcaggtccgcagtggaggccacatcaactcggcgccttgggaaccgctcgagcctaccagattccagagtcattaaaaa
60	Homo sapiens	74	1201	1128	683	NA	7p15-p12	cgcgtccgccccgcgagcacagagcctcgcctttgccgatccgccgcccgtccacacccgccgccagctcaccatggatgatgatatcgccgcgctcgtcgtcgacaacggctccggcatgtgcaaggccggcttcgcgggcgacgatgccccccgggccgtcttcccctccatcgtggggcgccccaggcaccagggcgtgatggtgggcatgggtcagaaggattcctatgtgggcgacgaggcccagagcaa
71	Homo sapiens	75	1202	1128	687	NA	17q25	gtctcagtcgccgctgccagctctcgcactctgttcttccgccgctccgccgtcgcgtttctctgccggtcgcaatggaagaagagatcgccgcgctggtcattgacaatggctccggcatgtgcaaagctggttttgctggggacgacgctccccgagccgtgtttccttccatcgtcgggcgccccagacaccagggcgtcatggtgggcatgggccagaaggactcctacgtgggcgacgaggcccagagca
142	Homo sapiens	160	3204	3045	1561	NA	1q41-q42	aatctatcagggaacggcggtggccggtgcggcgtgttcggtgcgctctggccgctcaggccgtgcggctgggtgagcgcacgcgaggcggcgaggcggcaagcgtgtttctaggtcgtggcgtcgggcttccggagctttggcggcagctaggggaggatggcggagtcttcggataagctctatcgagtcgagtacgccaagagcgggcgcgcctcttgcaagaaatgcagcgagagcatccccaaggactcg
182	Homo sapiens	414	4070	3657	1972	NA	20p12.1-p11.23	ctgcggccggcccgcgagctaggctgggtttttttttttctcccctccctcccccctttttccatgcagctgatctaaaagggaataaaaggctgcgcataatcataataataaaagaaggggagcgcgagagaaggaaagaaagccgggaggtggaagaggagggggagcgtctcaaagaagcgatcagaataataaaaggaggccgggctctttgccttctggaacgggccgctcttgaaagggcttttgaaa
190	Homo sapiens	1	1413	1413	892	NA	Xp21.3-p21.2	atggcgggcgagaaccaccagtggcagggcagcatcctctacaacatgcttatgagcgcgaagcaaacgcgcgcggctcctgaggctccagagacgcggctggtggatcagtgttggggctgttcgtgcggcgatgagcccggggtgggcagagaggggctgctgggcgggcggaacgtggcgctcctgtaccgctgctgcttttgcggtaaagaccacccacggcagggcagcatcctctacagcatgctgacg
196	Homo sapiens	644	3190	2547	1071	NA	7p15	attcagccggtgcgcgcggcggcgggaggcagtggctggggagtcccgtcgacgctctgttccgagagcgtgccccggaccgccagctcagaacaggggcagccgtgtagccgaacggaagctgggagcagccgggactggtggcccgcgcccgagctccgcaggcgggaagcaccctggatttgggaagtcccgggagcagcgcggcggcacctccctcacccaaggggccgcggcgacggtcacggggcgcgg
199	Homo sapiens	75	518	444	211	NA	6p21.3	gagagaaggagagcctgcagacagaggcctccagcttggtctgtctccccacctctaccagcatctgctgagctatgagccaaaccagggatttacagggaggaaaagctttcggactgctgaaggcccagcaggaagagaggctggatgagatcaacaagcaattcctagacgatcccaaatatagcagtgatgaggatctgccctccaaactggaaggcttcaaagagaaatacatggagtttgaccttaatggaaatggcgatattgatatcatgtccctgaaacgaatgctggagaaacttggagtccccaagactcacctagagctaaagaaattaattggagaggtgtccagtggctccggggagacgttcagctaccctgactttctcaggatgatgctgggcaagagatctgccatcctaaaaatgatcctgatgtatgaggaaaaagcgagagaaaaggaaaagccaacaggccccccagccaagaaagctatctctgagttgccctgatttgaagggaaaagggatgatgggattgaaggggcttctaatgacccagatatggaaacagaagacaaaattgtaagccagagtcaacaaattaaataaattaccccctcctccagatcaa
207	Homo sapiens	199	1641	1443	859	NA	14q32.32	atcctgggacagggcacagggccatctgtcaccaggggcttagggaaggccgagccagcctgggtcaaagaagtcaaaggggctgcctggaggaggcagcctgtcagctggtgcatcagaggctgtggccaggccagctgggctcggggagcgccagcctgagaggagcgcgtgagcgtcgcgggagcctcgggcaccatgagcgacgtggctattgtgaaggagggttggctgcacaaacgaggggagtacatc
208	Homo sapiens	204	1649	1446	844	NA	19q13.1-q13.2	gaattccagcggcggcgccgttgccgctgccgggaaacacaaggaaagggaaccagcgcagcgtggcgatgggcgggggtagagccccgccggagaggctgggcggctgccggtgacagactgtgccctgtccacggtgcctcctgcatgtcctgctgccctgagctgtcccgagctaggtgacagcgtaccacgctgccaccatgaatgaggtgtctgtcatcaaagaaggctggctccacaagcgtggtgaat
</pre>
</body>
</html>
